// sidebars.ts

import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import apiSidebar from "./docs/sidebar"; // make sure path is correct and relative to root


const cleanedItems = (apiSidebar as any[]).filter(
  (item) => !(item.type === "doc" && item.id === "freepower-api")
);

const sidebars: SidebarsConfig = {
  docs: [
    // { type: "autogenerated", dirName: "." },
    {
      type: "category",
      label: "API",
      items: cleanedItems as any, // cast to any if TypeScript complains
    },
  ],
};

export default sidebars;