// sidebars.ts

import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  api: [
    {
      type: 'doc',
      id: 'index'
    },
    { type: "autogenerated", dirName: "api" }],
};


export default sidebars;